#!/usr/bin/env ruby

require '~/bin/ThreadedProcessor'

class DoThumbs50 < ThreadedFileProcessorImageMagik

  def GetArgs()
    return "-resize 50%"
  end

  def GetSuffix()
    return "small"
  end

end

obj = DoThumbs50.new
obj.Run ARGV
